plugins {
	id 'org.springframework.boot' version '3.1.0' // Certifique-se de que está atualizado
	id 'io.spring.dependency-management' version '1.1.2'
	id 'java'
}

group = 'br.com.seteideias'
version = '1.0.0'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

jar {
	enabled = true // Garante que um `.jar` será gerado
	archiveBaseName.set('app') // Define o nome do `.jar` como `app.jar`
	archiveVersion.set('') // Remove a versão do nome do arquivo
	archiveClassifier.set('') // Garante que não haverá sufixos extras
	manifest {
		attributes 'Main-Class': 'br.com.seteideias.kotlindeployecr.Application' // Certifique-se de que está correto
	}
}
