plugins {
	id 'org.springframework.boot' version '3.1.0'
	id 'io.spring.dependency-management' version '1.1.2'
	id 'org.jetbrains.kotlin.jvm' version '1.9.21'
	id 'org.jetbrains.kotlin.plugin.spring' version '1.9.21'
}

group = 'br.com.seteideias.kotlindeployecr'
version = '1.0.0'

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(17)) // Garante que o Java use a versão 17
	}
}

kotlin {
	jvmToolchain(17) // Garante que o Kotlin use a versão 17 também
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootJar {
	mainClass.set('br.com.seteideias.kotlindeployecr.KotlindeployecrApplication')
}

jar {
	enabled = true
	archiveBaseName.set('app')
	archiveVersion.set('')
	archiveClassifier.set('')
	manifest {
		attributes 'Main-Class': 'br.com.seteideias.kotlindeployecr.KotlindeployecrApplication'
	}
}
